---
- name: Creating the directory to copy artifact to
  become: yes
  file:
    path: "/var/www"
    state: directory
    mode: 0644

- name: Copy operation
  tags: checksum
  block:
    - name: Checksum of original file
      stat:
        path: files/artifact.tar.gz
        checksum_algorithm: sha1
      register: src_info

    - name: Copy the zipped artifact
      become: yes
      copy:
        src: files/artifact.tar.gz
        dest: /var/www/artifact.tar.gz
        checksum:
      register: copy_out

    - name: Fail if copy was a failure
      fail:
        msg: "File Copy failed!"
      when: src_info.stat.checksum != copy_out.checksum

    - name: Print Copy successful
      debug:
        msg: "File copy Successful!"

# - name: Extract zipped artifact
#   become: yes
#   shell: |
#     tar xvf /var/www/artifact.tar.gz

- name: Extract zipped artifact
  unarchive:
    src: /var/www/artifact.tar.gz
    dest: /var/www/
    remote_src: True

- name: Start Backend Application
  become: yes
  shell: |
    cd /var/www/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
