---
- name: Creating the directory to copy artifact to
  become: yes
  file:
    path: "/var/www/backend"
    state: directory
    mode: 0644

- name: Copy the zipped artifact
  become: yes
  copy:
    src: "files/artifact.tar.gz"
    dest: /var/www/artifact.tar.gz

- name: Extract zipped artifact
  become: yes
  shell: |
    tar xvf /var/www/artifact.tar.gz

- name: Start Backend Application
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
