---
- name: Creating the directory to copy artifact to
  file:
    path: "/var/www/backend"
    state: directory
    mode: 0755

- name: Copy the zipped artifact
  become: yes
  copy:
    src: ~/project/backend/artifact.tar.gz
    dest: /var/www/artifact.tar.gz

- name: Extract zipped artifact
  shell: |
    tar xvf /var/www/artifact.tar.gz

- name: Start Backend Application
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
