---
- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: ~/node_exporter-1.3.1.linux-amd64.tar.gz

- name: "Uncompress node exporter."
  become: yes
  unarchive:
    src: ~/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: ~/
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: yes
  copy:
    src: ~/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: "0777"

- name: "add node exporter configuration."
  become: yes
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes
